name: azure_notification_hub_flutter
description: Flutter plugin for Azure Notification Hubs
version: 0.0.1
homepage: https://github.com/bridgeheadit/azure-notification-hub-flutter
repository: https://github.com/bridgeheadit/azure-notification-hub-flutter
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.bridgeheadit.azure_notification_hub_flutter
    pluginClass: AzureNotificationHubFlutterPlugin